services:
  be_postgres:
    image: postgres:16-alpine
    container_name: be_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${BE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BE_POSTGRES_DB}
    ports:
      - "${BE_POSTGRES_PORT}:5432"
    volumes:
      - be_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${BE_POSTGRES_USER} -d ${BE_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n_postgres:
    image: postgres:16-alpine
    container_name: n8n_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${N8N_POSTGRES_USER}
      POSTGRES_PASSWORD: ${N8N_POSTGRES_PASSWORD}
      POSTGRES_DB: ${N8N_POSTGRES_DB}
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${N8N_POSTGRES_USER} -d ${N8N_POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    depends_on:
      n8n_postgres:
        condition: service_healthy
    ports:
      - "${N8N_PORT}:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: n8n_postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${N8N_POSTGRES_DB}
      DB_POSTGRESDB_USER: ${N8N_POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${N8N_POSTGRES_PASSWORD}

      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: 5678
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}

      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      TZ: ${TZ}

      N8N_RUNNERS_ENABLED: "true"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE}
      N8N_PROXY_HOPS: ${N8N_PROXY_HOPS}
    volumes:
      - n8n_data:/home/node/.n8n

  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3100:8080"
    volumes:
      - open-webui:/app/backend/data

volumes:
  be_postgres_data:
  n8n_postgres_data:
  n8n_data:
  open-webui:
